csgoh/roadmapper

- .github/workflows/ci.yaml
This GitHub Actions workflow triggers pytest in `src/tests/`. It triggers the execution on each PR and on every push to the main branch. The tests run on Ubuntu with Python `3.10` and `3.11`.
To ensure that everything gets tested, we should add this workflow as a requirement for every PR to pass.
Currently, the workflow installs the fonts on the testing system. As this requires some execution time, the installation should be cached. Alternatively, #20 wants the requirement of a specific font to be removed.
> Create GH Actions workflow for pre-merge

- .github/workflows/ci.yaml
- pyproject.toml
- src/tests/roadmap_draw_test.py
In this PR, I add some config for PyTest in the `pyproject.toml`. Namely, I set the test output to verbose to show some more details when running the tests. Additionally, I introduce `markers` as they allow us to run specific test groups. With this feature, we can run tests specific to certain platforms (which will be needed by my next PR). 
If we now run `pytest -m 'unit'`, we only trigger the tests which have the marker `unit`. For marking several tests in a file, these tests should be grouped together in a class. Currently, I only marked one test with `unit` because the other tests are quite messy and do not really _test_ specifics.
> Add pytest markers to focus only on unit tests

- src/tests/compare_generated_roadmaps_test.py
- src/tests/conftest.py
- src/tests/roadmap_generators/roadmap_generator.py
With this PR, I introduce another variable in the OS-specific tests to easily allow recreating these tests for other OSs. Currently, the OS var is only available as `Ubuntu` and can be retrieved via the fixture `operating_system_ubuntu`. In the future, the value of the OS var should be tied to the used marker.
In addition, I use this PR to adapt method names and order to increase readability. This also included removing the unused method `get_all_roadmap_names_to_generate` and slimming the method `generate_and_save_all_roadmaps_in`.
> Enable OS agnostic tests

- .github/workflows/generate_examples.yaml
With this PR, it also becomes possible to execute the manual action to generate roadmaps on Windows. As Windows requires specific Powershell code, I had to add a specific step for the Windows runner.
> Add Powershell code to also generate roadmaps on Windows

- .github/workflows/ci.yaml
Similar to `*.png`, we can now also ignore changes in `*.svg`.
> Ignore changes in `*.svg`

- .github/workflows/ci.yaml
- .github/workflows/generate_examples.yaml
Version 2 of the checkout action uses node12 which is deprecated and will be forced to run on node16. The main change of version 3 is to use node16.
> Bumb `actions/checkout` to enforce later node version

- .github/workflows/ci.yaml
The only difference between the two ways of installing the requirements for Windows and non-Windows was the `if` statement (Bash and PowerShell). The `if` statement results in installing the requirements only if the `requirements.txt` is present. With or without the `if` statement, the CI build would fail without the `requirements.txt` not being present. Therefore, we do not require this check and can simplify the workflow file.
> Simplify dependency installation by treating all OSs same way

- pyproject.toml
Adding this marker to the file `pyproject.toml` removes the warning about a missing marker.
> Add missing pytest marker for tests on OS Windows

- .github/workflows/ci.yaml
- src/tests/compare_generated_roadmaps_test.py
In this PR, I finally add the functionality to upload the diffs between the generated roadmaps of the tests and the example roadmaps. This gives devs the opportunity to investigate the difference between how the roadmaps should look and how their generated roadmaps look like.
> Upload diffs in case of previous test failure

- .github/workflows/generate_examples.yaml
Discovered that we still use an action with an old node version...
> Bump version of `upload-artifact`

- .github/workflows/ci.yaml
As Python version `3.12` recently reached GA status, we should start testing on this version as well.
> Include tests on Python 3.12

- .github/workflows/ci.yaml
- .github/workflows/generate_examples.yaml
- .github/workflows/lint.yaml
A few weeks back, the checkout action was updated to version `4`. As they already released the first minor upgrade to version `4.1.1`, minor issues should be removed already.
> chore: update checkout action to version `4`

- src/tests/test_painter.py
I discovered that we have some more unit tests. They should receive the Pytest marker `unit` to be automatically executed in our CI workflow.
> Add tests in `test_painter.py` to Pytest marker `unit`

- .github/workflows/ci.yaml
- .github/workflows/generate_examples.yaml
We can upgrade the usage of `actions/upload-artifact` to version `4`. As the action already [received some minor version releases](https://github.com/actions/upload-artifact/releases), it should be safe to upgrade. According to the [migration guide for the version upgrade](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), we do not require any logic changes. 
The tests will only succeed after emerging PR #81. When this PR is merged into the `main` branch, retrigger just retrigger the tests.
> chore: upgrade to version `4` of `actions/upload-artifact`

- .github/workflows/ci.yaml
- .github/workflows/generate_examples.yaml
[Node.js version 16 has reached EOL](https://github.com/nodejs/Release/#end-of-life-releases) and GH Actions with it are deprecated. [Version 5 of `actions/setup-python` was released in early December 2023](https://github.com/actions/setup-python/releases/tag/v5.0.0) with [using Node.js 20](https://github.com/actions/setup-python/pull/772). As the release did not introduce other significant changes, we can easily upgrade to the latest major version 5.
> ci: bump `actions/setup-python` to version `5`

- ci/version_retriever.py
- pyproject.toml
This script allows to retrieve the current source code version. This functionality will be used later on to bump the version automatically.
> ci: add ability to retrieve current version

- ci/version_determiner.py
This script adds the functionality to determine the future version the lib should be bumped to. It allows to determine the next release version, its version tag, and the snapshot version required after the release. These different version numbers can be determined for the releases `PATCH`, `MINOR` and `MAJOR`.
> ci: add ability to determine future versions

- ci/version_writer.py
After determining the new version, this script enables writing the new version to the version file. This script does not check anything about the version, i.e. it sets the new version to whatever you tell it.
> ci: add functionality to write new versions for lib

- .github/workflows/manual_release_trigger.yaml
This GH Actions workflow uses the previously created script to bump the versions automatically. The workflow can be triggered manually as a `workflow_dispatch`, and you just have to give it the input of wanting to do a patch release, a minor release, or a major release. It then bumps to the appropriate release version, commits it and tags it. Afterwards, it automatically bumps the version to the next snapshot version.
As the new release version is tagged, a release can be created when checking out this tag.
> ci: add manual trigger to bump the versions accordingly

- .github/workflows/release-on-github.yaml
* This workflow can be called either directly via the web UI or indirectly via another workflow.
* This worflow always requires a Git tag as an input to create a release of this exact tag.
> ci: add workflow to release on GitHub

- .github/workflows/release.yaml
* This workflow gets automatically triggered on any tag push if the tag starts with `v*`.
* This workflow builds and deploys the lib to PyPI with Twine.
* After a successful deployment to PyPI, the workflow calls another workflow to issue a GitHub release.
> ci: add workflow to automatically release to PyPI and GitHub

- .github/workflows/lint.yaml
- pyproject.toml
According to the warning from Ruff `warning: The top-level linter settings are deprecated in favour of their counterparts in the 'lint' section.`, the linter settings should be adjusted. I moved our linter ignore settings from the top level to the level `linter`.
With the previous PRs, I introduced the new directory `ci/`. I added this directory to Rust's linter parsing.
> ci: improve linter

- src/tests/compare_generated_roadmaps_test.py
I found this nice way to parameterise every method in a whole class. It's purely a refactor without introducing new functionality.
> refactor: parameterise whole test class
